stages:
  - build

variables:
  REGISTRY_ENDPOINT: "cr.yandex"
  UPSTREAM_DB_IMAGE: "postgres:17"
  TARGET_DB_NAME: "db"
  TARGET_API_NAME: "ts-api"
  REGISTRY_ID: "crp76t66v12au4b36gbk" 

build-api:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY_ENDPOINT\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${REGISTRY_ENDPOINT}/${REGISTRY_ID}/${TARGET_API_NAME}:${CI_COMMIT_SHA}"
      --destination "${REGISTRY_ENDPOINT}/${REGISTRY_ID}/${TARGET_API_NAME}:latest"
      --cache=true
