FROM nginx:1.27-alpine
COPY ui/nginx.conf /etc/nginx/conf.d/default.conf
COPY ui/index.html /usr/share/nginx/html/index.html
COPY ui/config.js /usr/share/nginx/html/config.js
COPY ui/static /usr/share/nginx/html/static
EXPOSE 80
