[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "catboost>=1.2.10",
    "darts>=0.45.0",
    "fastapi>=0.140.0",
    "ipykernel>=7.3.0",
    "kagglehub>=1.0.2",
    "lightgbm>=4.6.0",
    "mlflow>=3.14.0",
    "python-multipart>=0.0.32",
    "openpyxl>=3.1.5",
    "optuna>=4.9.0",
    "pandas>=2.3.3",
    "pyarrow>=24.0.0",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "shap>=0.52.0",
    "uvicorn>=0.51.0",
    "psycopg2>=2.9.12",
]

[dependency-groups]
deploy = [
    "fastapi>=0.140.0",
    "jinja2>=3.1.0",
    "lightgbm>=4.6.0",
    "pandas>=2.3.3",
]
